# Remplacer point_cloud_topic par ceci :
input_sources:
  ouster_lidar:
    type: pointcloud
    topic: /ouster/points
    queue_size: 10
    publish_on_update: true
    sensor_processor:
      type: perfect

map_frame_id: "world"
robot_base_frame_id: "base"
robot_pose_with_covariance_topic: ""
robot_pose_cache_size: 200

track_point_frame_id: "base"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
min_update_rate: 10.0
time_tolerance: 0.2

length_in_x: 10.0
length_in_y: 10.0
resolution: 0.1
min_variance: 0.0001
max_variance: 0.05
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
enable_visibility_cleanup: false
