# ================== joint_state_controller ==================
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# ================== PID profiles (front legs stiffer) ==================
F_HFE: &F_HFE
  p: 200.0
  i: 0.0       
  d: 4.5
  i_clamp: 4.0

F_KFE: &F_KFE
  p: 200.0
  i: 0.0
  d: 4.0
  i_clamp: 4.0

H_HFE: &H_HFE
  p: 200.0
  i: 0.0
  d: 4.0
  i_clamp: 4.0

H_KFE: &H_KFE
  p: 200.0
  i: 0.0
  d: 4.0
  i_clamp: 4.0

F_HAA: &F_HAA
  p: 250.0
  i: 0.0
  d: 1.0
  i_clamp: 4.0

R_HAA: &R_HAA
  p: 250.0
  i: 0.0
  d: 1.0
  i_clamp: 4.0

F_AFE: &F_AFE
  p: 150.0
  i: 0.0
  d: 1.0
  i_clamp: 4.0

H_AFE: &H_AFE
  p: 150.0
  i: 0.0
  d: 1.0
  i_clamp: 4.0

# ===========================================================

# ===========================================================

# =========== Front Left Leg (FL) ===========
FL_HAA_position_controller:
  type: effort_controllers/JointPositionController
  joint: FL_HAA
  pid: *F_HAA
  command: 0.0

FL_HFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: FL_HFE
  pid: *F_HFE
  command: 0.4102

FL_KFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: FL_KFE
  pid: *F_KFE
  command: -1.2716

# =========== Front Right Leg (FR) ===========
FR_HAA_position_controller:
  type: effort_controllers/JointPositionController
  joint: FR_HAA
  pid: *F_HAA
  command: 0.0

FR_HFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: FR_HFE
  pid: *F_HFE
  command: 0.4102

FR_KFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: FR_KFE
  pid: *F_KFE
  command: -1.2716

# =========== Hind Left Leg (HL) ===========
HL_HAA_position_controller:
  type: effort_controllers/JointPositionController
  joint: HL_HAA
  pid: *R_HAA
  command: 0.0

HL_HFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: HL_HFE
  pid: *H_HFE
  command: -0.6981

HL_KFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: HL_KFE
  pid: *H_KFE
  command: 1.676

HL_AFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: HL_AFE
  pid: *R_HAA
  command: -1.7219

# =========== Hind Right Leg (HR) ===========
HR_HAA_position_controller:
  type: effort_controllers/JointPositionController
  joint: HR_HAA
  pid: *R_HAA
  command: 0.0

HR_HFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: HR_HFE
  pid: *H_HFE
  command: -0.6981

HR_KFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: HR_KFE
  pid: *H_KFE
  command: 1.676

HR_AFE_position_controller:
  type: effort_controllers/JointPositionController
  joint: HR_AFE
  pid: *R_HAA
  command: -1.7219

